apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployments
  labels:
    app: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask
        image: zsq89/try-flask:latest
        ports:
        - containerPort: 5000
